### ISSUE TITLE
Conflicts in requirements.txt

### ISSUE THREAD

**Issue by fdila** [AlvinWen428/FeatureCP#2]
Hello,
I'm trying to install the required python packages to run the code.
However, it appears that the versions specified in the requirements for torch and auto-lirpa conflict with each other:

The conflict is caused by:
    The user requested torch==1.7.1
    auto-lirpa 0.2 depends on torch<1.9.0 and >=1.8.0

Do you know how to solve this issue? I tried using a newer version of torch, but it caused issues at runtime.

**Comment by Soothysay** [comment]
Faced the same issue. Tried multiple versions of torch. But the run instructions throw errors.

**Comment by AlvinWen428** [comment]
Sorry for the late response. I checked my environment and ensure that torch==1.7.1 and auto-lirpa==0.2 work for me. If you meet conflicting error when using `pip install`, you can comment out the pytorch part in requirements.txt to first install other packages. Then run `pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 -f https://download.pytorch.org/whl/torch_stable.html`.
